# Generated by Django 4.2.7 on 2025-09-26 21:27

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('owner', 'Dueño de Establecimiento'), ('artist', 'Artista/Emprendedor')], max_length=10, verbose_name='Tipo de Usuario')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('profile_image', models.ImageField(blank=True, upload_to='profiles/', verbose_name='Imagen de Perfil')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video')], default='image', max_length=5)),
                ('file', models.FileField(upload_to='profile_media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nombre del Negocio')),
                ('business_type', models.CharField(max_length=100, verbose_name='Tipo de Negocio')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('capacity', models.IntegerField(verbose_name='Capacidad')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('contact_alt', models.CharField(blank=True, max_length=100, verbose_name='Contacto Alternativo')),
                ('schedule', models.CharField(blank=True, max_length=200, verbose_name='Horarios de Funcionamiento')),
                ('additional_services', models.JSONField(blank=True, null=True, verbose_name='Servicios Adicionales')),
                ('hiring_policies', models.TextField(blank=True, verbose_name='Políticas de Contratación')),
                ('cuit_cuil', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Formato CUIT/CUIL: XX-XXXXXXXX-X', regex='^\\d{2}-\\d{8}-\\d{1}$')], verbose_name='CUIT/CUIL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propietario de Establecimiento',
                'verbose_name_plural': 'Propietarios de Establecimientos',
            },
        ),
        migrations.CreateModel(
            name='ArtistEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=100, verbose_name='Nombre Artístico')),
                ('category', models.CharField(choices=[('musician', 'Músico'), ('band', 'Banda'), ('dj', 'DJ'), ('comedian', 'Comediante'), ('photographer', 'Fotógrafo'), ('gastronomic', 'Gastronómico'), ('other', 'Otro')], max_length=20, verbose_name='Categoría')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Años de Experiencia')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='URL del Portfolio')),
                ('bio', models.TextField(blank=True, verbose_name='Breve Descripción')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('tiktok', models.CharField(blank=True, max_length=100, verbose_name='TikTok')),
                ('other_socials', models.CharField(blank=True, max_length=200, verbose_name='Otras Redes')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('availability', models.JSONField(blank=True, null=True, verbose_name='Disponibilidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artista/Emprendedor',
                'verbose_name_plural': 'Artistas/Emprendedores',
            },
        ),
    ]
